In [69]:
import sqlite3
import pandas as pd

In [81]:
conexao = sqlite3.connect('status_brasil')
dados = pd.read_excel('../tabelas_excel/planilha_modulo3.xlsx')

In [9]:
pd.read_sql("SELECT regiao FROM Municipios_Brasileiros;", con=conexao)

     Regiao
0     Norte
1     Norte
2     Norte
3     Norte
4     Norte
...     ...
5554  Norte
5555  Norte
5556  Norte
5557  Norte
5558  Norte

[5559 rows x 1 columns]

In [10]:
pd.read_sql("SELECT * FROM Municipios_Brasileiros WHERE Cidade = 'Itaquaquecetuba';", con=conexao)

            Cidade Estado   Regiao  Municipio_ID
0  Itaquaquecetuba     SP  Sudeste          5043

In [11]:
pd.read_sql("SELECT * FROM Municipios_Brasileiros WHERE Cidade like 'Itaqua%';", con=conexao)

            Cidade Estado    Regiao  Municipio_ID
0         Itaquara     BA  Nordeste           399
1  Itaquaquecetuba     SP   Sudeste          5043

In [18]:
pd.read_sql("""SELECT Municipios_Brasileiros.Cidade, Municipio_Status.populacao_residente 
            FROM Municipios_Brasileiros 
            INNER JOIN Municipio_Status 
            ON Municipios_Brasileiros.Municipio_ID = Municipio_Status.municipio_id;""", con=conexao)

               Cidade  populacao_residente
0         AcrelÃ¢ndia                 2538
1        Assis Brasil                 6072
2          BrasilÃ©ia                21398
3              Bujari                 8471
4            Capixaba                 8798
...               ...                  ...
5554  TocantinÃ³polis                22619
5555         Tupirama                 1574
5556       Tupiratins                 2097
5557    WanderlÃ¢ndia                10981
5558         XambioÃ¡                11484

[5559 rows x 2 columns]

In [19]:
pd.read_sql("SELECT * FROM Municipio_Status WHERE populacao_residente > 50000;", con=conexao)

     status_ID  populacao_residente  IDHM_rank  educacao  renda  municipio_id
0            6                78507       2820     0.582  0.648             6
1           16               336038       1116     0.661  0.729            16
2           25               214006       3143     0.549  0.638            25
3           37                50816       4862     0.470  0.531            37
4           46                52130       3571     0.541  0.591            46
..         ...                  ...        ...       ...    ...           ...
603       5419               108809        266     0.747  0.720          5419
604       5420                84692         67     0.744  0.772          5420
605       5433               150484        512     0.712  0.727          5433
606       5480                76755        398     0.706  0.736          5480
607       5510               228332         84     0.749  0.789          5510

[608 rows x 6 columns]

In [21]:
pd.read_sql("""SELECT Estado, COUNT(Cidade) 
            FROM Municipios_Brasileiros 
            GROUP BY Estado 
            ORDER BY 2 DESC;""", con=conexao)

   Estado  COUNT(Cidade)
0      MG            852
1      SP            646
2      RS            496
3      BA            416
4      PR            399
5      SC            293
6      GO            245
7      PI            224
8      PB            222
9      MA            217
10     PE            185
11     CE            184
12     RN            164
13     PA            143
14     MT            141
15     TO            138
16     AL            102
17     RJ             93
18     MS             78
19     ES             78
20     SE             75
21     AM             62
22     RO             52
23     AC             22
24     AP             16
25     RR             15
26     DF              1

In [22]:
pd.read_sql("SELECT SUM(pessoas_brancas), SUM(pessoas_pretas_pardas) FROM Gerencia_Regiao;", con=conexao)

   SUM(pessoas_brancas)  SUM(pessoas_pretas_pardas)
0                 43349                       52580

In [ ]:
pd.read_sql("""SELECT Estado, COUNT(Cidade) 
            FROM Municipios_Brasileiros 
            GROUP BY Estado 
            ORDER BY 2 DESC;""", con=conexao)

In [24]:
pd.read_sql("SELECT Regiao, MAX(pessoas_pretas_pardas) FROM Gerencia_Regiao;", con=conexao)

    regiao  MAX(pessoas_pretas_pardas)
0  Sudeste                       20783

In [26]:
pd.read_sql("SELECT Regiao, MIN(pessoas_pretas_pardas) FROM Gerencia_Regiao;", con=conexao)

  regiao  MIN(pessoas_pretas_pardas)
0    Sul                        3945

In [27]:
pd.read_sql("SELECT Regiao FROM Gerencia_Regiao WHERE gerencia_branca > gerencia_preta_parda", con=conexao)

         regiao
0       Sudeste
1           Sul
2  Centro-Oeste

In [31]:
pd.read_sql("""SELECT mb.Estado, SUM(ms.populacao_residente) as total_habitantes 
            FROM Municipios_Brasileiros mb
            INNER JOIN Municipio_Status ms
            ON ms.municipio_id = mb.Municipio_ID
            GROUP BY mb.Estado
            ORDER BY total_habitantes ASC""", con=conexao)

   Estado  total_habitantes
0      RR            450479
1      AP            669526
2      AC            723559
3      TO           1375062
4      RO           1562409
5      SE           2068017
6      MS           2449024
7      DF           2570160
8      MT           3035122
9      RN           3096500
10     PI           3118360
11     AL           3120494
12     AM           3483985
13     ES           3514952
14     PB           3763673
15     GO           5983061
16     SC           6248436
17     MA           6574789
18     PA           7581051
19     CE           8452381
20     PE           8796448
21     PR          10447889
22     RS          10693929
23     BA          14007258
24     RJ          16027462
25     MG          19592277
26     SP          41357343

In [32]:
pd.read_sql("""SELECT mb.Estado, avg(ms.renda) as media_renda_por_estado
            FROM Municipios_Brasileiros mb
            INNER JOIN Municipio_Status ms
            ON ms.municipio_id = mb.Municipio_ID
            GROUP BY mb.Estado""", con=conexao)

   Estado  media_renda_por_estado
0      AC                0.585455
1      AL                0.548363
2      AM                0.545113
3      AP                0.618875
4      BA                0.574805
5      CE                0.559293
6      DF                0.863000
7      ES                0.680628
8      GO                0.683980
9      MA                0.531664
10     MG                0.652008
11     MS                0.687846
12     MT                0.682149
13     PA                0.572357
14     PB                0.564423
15     PE                0.574378
16     PI                0.546813
17     PR                0.691915
18     RJ                0.704796
19     RN                0.580183
20     RO                0.658173
21     RR                0.577867
22     RS                0.722115
23     SC                0.728038
24     SE                0.577147
25     SP                0.716571
26     TO                0.610543

In [82]:
lista_estados = list(dados['UF ONDE MORA'].unique())

query = """SELECT mb.Estado, avg(ms.renda) as media_renda_por_estado
            FROM Municipios_Brasileiros mb
            INNER JOIN Municipio_Status ms
            ON ms.municipio_id = mb.Municipio_ID
            WHERE mb.Estado IN ({})
            GROUP BY mb.Estado;""".format(','.join(['?' for _ in lista_estados]))

estado_renda = pd.read_sql(query, con=conexao, params=lista_estados)

In [ ]:
dados.rename(columns={'UF ONDE MORA': 'Estado'}, inplace=True)

In [84]:
dados.columns

Index(['Unnamed: 0', 'ID', 'IDADE', 'FAIXA IDADE', 'GENERO', 'COR/RACA/ETNIA',
       'PCD', 'EXPERIENCIA_PROFISSIONAL_PREJUDICADA', 'ASPECTOS_PREJUDICADOS',
       'VIVE_NO_BRASIL', 'ESTADO ONDE MORA', 'Estado', 'REGIAO ONDE MORA',
       'MUDOU DE ESTADO?', 'REGIAO DE ORIGEM', 'NIVEL DE ENSINO',
       'ÁREA DE FORMAÇÃO', 'QUAL SUA SITUAÇÃO ATUAL DE TRABALHO?', 'SETOR',
       'NUMERO DE FUNCIONARIOS', 'GESTOR?', 'CARGO COMO GESTOR', 'CARGO ATUAL',
       'NIVEL', 'FAIXA SALARIAL',
       'QUANTO TEMPO DE EXPERIÊNCIA NA ÁREA DE DADOS VOCÊ TEM?',
       'QUANTO TEMPO DE EXPERIÊNCIA NA ÁREA DE TI/ENGENHARIA DE SOFTWARE VOCÊ TEVE ANTES DE COMEÇAR A TRABALHAR NA ÁREA DE DADOS?',
       'SALARIO'],
      dtype='str')

In [88]:
dados = dados.merge(estado_renda, on="Estado", how='left')

In [89]:
dados.columns

Index(['Unnamed: 0', 'ID', 'IDADE', 'FAIXA IDADE', 'GENERO', 'COR/RACA/ETNIA',
       'PCD', 'EXPERIENCIA_PROFISSIONAL_PREJUDICADA', 'ASPECTOS_PREJUDICADOS',
       'VIVE_NO_BRASIL', 'ESTADO ONDE MORA', 'Estado', 'REGIAO ONDE MORA',
       'MUDOU DE ESTADO?', 'REGIAO DE ORIGEM', 'NIVEL DE ENSINO',
       'ÁREA DE FORMAÇÃO', 'QUAL SUA SITUAÇÃO ATUAL DE TRABALHO?', 'SETOR',
       'NUMERO DE FUNCIONARIOS', 'GESTOR?', 'CARGO COMO GESTOR', 'CARGO ATUAL',
       'NIVEL', 'FAIXA SALARIAL',
       'QUANTO TEMPO DE EXPERIÊNCIA NA ÁREA DE DADOS VOCÊ TEM?',
       'QUANTO TEMPO DE EXPERIÊNCIA NA ÁREA DE TI/ENGENHARIA DE SOFTWARE VOCÊ TEVE ANTES DE COMEÇAR A TRABALHAR NA ÁREA DE DADOS?',
       'SALARIO', 'media_renda_por_estado'],
      dtype='str')

In [91]:
correlacao_renda_salario = dados['SALARIO'].corr(dados['media_renda_por_estado'])
correlacao_renda_salario

np.float64(0.07248950401807587)